/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as RoundsRouteImport } from './routes/rounds'
import { Route as PrizesRouteImport } from './routes/prizes'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundsRoute = RoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizesRoute = PrizesRouteImport.update({
  id: '/prizes',
  path: '/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/prizes': typeof PrizesRoute
  '/rounds': typeof RoundsRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/prizes': typeof PrizesRoute
  '/rounds': typeof RoundsRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/prizes': typeof PrizesRoute
  '/rounds': typeof RoundsRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/faq' | '/prizes' | '/rounds' | '/sponsors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/faq' | '/prizes' | '/rounds' | '/sponsors'
  id: '__root__' | '/' | '/about' | '/faq' | '/prizes' | '/rounds' | '/sponsors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  PrizesRoute: typeof PrizesRoute
  RoundsRoute: typeof RoundsRoute
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rounds': {
      id: '/rounds'
      path: '/rounds'
      fullPath: '/rounds'
      preLoaderRoute: typeof RoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prizes': {
      id: '/prizes'
      path: '/prizes'
      fullPath: '/prizes'
      preLoaderRoute: typeof PrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  PrizesRoute: PrizesRoute,
  RoundsRoute: RoundsRoute,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
